# Generated by Django 5.0.14 on 2026-05-19 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, default='solar_tracker_01', max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('critical', 'Nghiêm trọng')], default='warning', max_length=16)),
                ('alert_type', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(default='auto', max_length=16)),
                ('azimuth', models.IntegerField(default=90)),
                ('elevation', models.IntegerField(default=90)),
                ('light_total', models.IntegerField(default=0)),
                ('rain', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trạng thái hệ thống',
                'verbose_name_plural': 'Trạng thái hệ thống',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, default='solar_tracker_01', max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ldr_tl', models.IntegerField(default=0)),
                ('ldr_tr', models.IntegerField(default=0)),
                ('ldr_bl', models.IntegerField(default=0)),
                ('ldr_br', models.IntegerField(default=0)),
                ('light_total', models.IntegerField(default=0)),
                ('azimuth', models.IntegerField(default=0)),
                ('elevation', models.IntegerField(default=0)),
                ('rain', models.BooleanField(default=False)),
                ('mode', models.CharField(default='auto', max_length=16)),
                ('wifi_rssi', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='tracker_sen_timesta_6d9bd0_idx'), models.Index(fields=['device_id', '-timestamp'], name='tracker_sen_device__4ed21f_idx')],
            },
        ),
    ]
