# Generated by Django 5.0.14 on 2026-05-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstate',
            name='target_azimuth',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='target_elevation',
            field=models.IntegerField(default=90),
        ),
    ]
